env:
  browser: true
  es2021: true
extends:
  - google
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
  max-len: ["error", { "code": 126 }],
  indent: ["error", 4],
  quotes: ["error", "double"],
  space-before-function-paren: ["error", {"anonymous": "always", "named": "never", "asyncArrow": "always"}],
  no-unused-vars: "off",
  camelcase: "off",
  "@typescript-eslint/no-unused-vars": "error"
}
